Montadora/Models/Fornecedor.cs
using Montadora.Repository;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Collections;

namespace Montadora.Models
{
    public class Fornecedor : Pessoa
    {
        [Display(Name="Endereço")]
        public string Endereco { get; set; }

        public void Save()
        {
            FornecedorRepository fornecedorRep = new FornecedorRepository();
            if (Id == 0)
            {
                fornecedorRep.Salvar(this);
            }
            else
            {
                fornecedorRep.Alterar(this);
            }
        }
        public Fornecedor FindById(int id)
        {            
            return new FornecedorRepository().BuscarPorID(id);         
        }

        public IList<Fornecedor> GetAll ()
        {
            return new FornecedorRepository().BuscarTodos();
        }

        public void Delete(Fornecedor f)
        {            
            new FornecedorRepository().Deletar(f);
        }
        public IList<Fornecedor> FindByName(string nomeBusca)
        {            
            return new FornecedorRepository().BuscarPorNome(nomeBusca);
        }
    }
}

Montadora/Controllers/FornecedorController.cs
using Montadora.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Montadora.Controllers
{
    public class FornecedorController : Controller
    {
        [HttpGet]
        public ActionResult Listar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Listar(string nomeBusca)
        {
            IList<Fornecedor> fornecedores = new Fornecedor().FindByName(nomeBusca);
            return PartialView("_ListarFornecedor", fornecedores);
        }
        [HttpPost]
        public ActionResult ListarFornecedoresPorPeca(string nome)
        {
            IList<Fornecedor> fornecedores = new Fornecedor().FindByName(nome);
            return PartialView("_ListarFornecedorPorPeca", fornecedores);
        }
        [HttpGet]
        public ActionResult Novo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Novo(Fornecedor f)
        {
            if (ModelState.IsValid)
            {
                f.Save();
                return RedirectToAction("Listar");
            }
            else
            {
                return View(f);
            }
        }
        [HttpGet]
        public ActionResult Deletar(int id)
        {
            Fornecedor objFornecedor = new Fornecedor().FindById(id);
            return View(objFornecedor);
        }
        [HttpPost]
        public ActionResult Deletar(Fornecedor objFornecedor)
        {
            objFornecedor.Delete(objFornecedor);
            return RedirectToAction("Listar");
        }
        [HttpGet]
        public ActionResult Editar(int id)
        {
            Fornecedor objFornecedor = new Fornecedor().FindById(id);
            return View(objFornecedor);
        }
        [HttpPost]
        public ActionResult Editar(Fornecedor objFornecedor)
        {
            objFornecedor.Save();
            return RedirectToAction("Listar");
        }
    }
}

Montadora/Views/Fornecedor/Deletar.cshtml
@model Montadora.Models.Fornecedor
@{
    ViewBag.Title = "Excluir Fornecedor";
}
<h2>Você deseja realmente excluir o Fornecedor: @Model.Nome ? </h2>
<hr />
@using (Html.BeginForm())
{
    @Html.HiddenFor(id => id.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.Nome): @Model.Nome
    </div>
    <div>
        @Html.LabelFor(model => model.Endereco): @Model.Endereco
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Cpf): @Model.Cpf
    </div>
    <div class="form-group">
        <div class="col-md-offset-1">
            <input type="submit" value="Excluir" class="btn btn-danger" />
            @Html.ActionLink("Cancelar", "Listar", "", new { @class = "btn btn-primary" })
        </div>
    </div>
}

Montadora/Views/Fornecedor/Editar.cshtml
@model Montadora.Models.Fornecedor
@{
    ViewBag.Title = "Editar Fornecedor";
}
<h2>Editar Fornecedor</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.HiddenFor(id => id.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.Nome)
        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Cpf)
        @Html.EditorFor(model => model.Cpf, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Endereco)
        @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        <div class="col-md-offset-1">
            <input type="submit" value="Salvar" class="btn btn-success" />
            @Html.ActionLink("Cancelar", "Listar", "", new { @class = "btn btn-default" })
        </div>
    </div>
}

Montadora/Views/Fornecedor/Listar.cshtml
@model Montadora.Models.Fornecedor
@{
    ViewBag.Title = "Buscar Fornecedores";
}
<h3>Buscar Fornecedores</h3>
<hr />
<div class="col-md-offset-11">
    <p>
        @Html.ActionLink(" ", "Novo", null, new { @class = " glyphicon glyphicon-plus btn btn-primary"})
    </p>
</div>

    <div class="row">
        <div class="col-md-3">
            <input type="text" name="nomeBusca" id="nomeBusca" class="form-control" placeholder="Informe o nome do fornecedor..." />
        </div>
        <div class="col-lg-offset-3">
            <button type="submit" id="buscar" onclick="click" class="btn btn-primary"><i class=" glyphicon glyphicon-search"></i></button>
        </div>
    </div>
<hr />

<div id="exibirFornecedores">

</div>


@section scripts{
    <script>
        $("#buscar").on("click", function () {
            var resultado = $("#nomeBusca").val();

            $("#exibirFornecedores").load('@Url.Action("Listar", "Fornecedor")', { teste: resultado })
        });
    </script>
}

Montadora/Views/Fornecedor/Novo.cshtml
@model Montadora.Models.Fornecedor
@{
    ViewBag.Title = "Novo Fornecedor";
}

<h2>Nova Fornecedor</h2>
<hr />
@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(model => model.Nome)
        @Html.TextBoxFor(model => model.Nome, new { @class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Cpf)
        @Html.TextBoxFor(model => model.Cpf, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Endereco)
        @Html.TextBoxFor(model => model.Endereco, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <div class="col-md-offset-1">
            <input type="submit" value="Salvar" class="btn btn-success" />
            @Html.ActionLink("Cancelar", "Listar", "", new { @class = "btn btn-default" })
        </div>
    </div>
}

Montadora/Views/Fornecedor/_ListarFornecedor.cshtml
@model IEnumerable<Montadora.Models.Fornecedor>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Nome)</th>
            <th>@Html.DisplayNameFor(model => model.Endereco)</th>
            <th>@Html.DisplayNameFor(model => model.Cpf)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(i => item.Nome)</td>
                <td>@Html.DisplayFor(i => item.Endereco)</td>
                <td>@Html.DisplayFor(i => item.Cpf)</td>
                <td>
                    @Html.ActionLink(" ", "Editar", new { id = item.Id }, new { @class = "glyphicon glyphicon-pencil btn btn-warning" })
                    @Html.ActionLink(" ", "Deletar", new { id = item.Id }, new { @class = "glyphicon glyphicon-trash btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>