Montadora/Controllers/PecaController.cs
using Montadora.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Montadora.Controllers
{
    public class PecaController : Controller
    {
        [HttpGet]
        public ActionResult Listar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Listar(string descricao)
        {
            IList<Peca> pecas = new Peca().FindByName(descricao);
            return PartialView("_ListarPecas", pecas);
        }

        [HttpGet]
        public ActionResult Novo()
        {
            ViewBag.Fornecedor = new SelectList(new Fornecedor().GetAll(), "Id", "Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Novo(Peca p)
        {
            p.Save();
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            Peca objPeca = new Peca().FindById(id);
            ViewBag.Fornecedor = new SelectList(new Fornecedor().GetAll(), "Id", "Nome");
            return View(objPeca);
        }

        [HttpPost]
        public ActionResult Editar(Peca p)
        {
            p.Save();
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Deletar(int id)
        {
            Peca objPeca = new Peca().FindById(id);
            return View(objPeca);
        }

        [HttpPost]
        public ActionResult Deletar(Peca p)
        {
            p.Deletar(p);
            return RedirectToAction("Listar");
        }
    }
}

Montadora/Controllers/VeiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Montadora.Controllers
{
    public class VeiculoController : Controller
    {
        // GET: Veiculo
        public ActionResult Index()
        {
            return View();
        }
    }
}

Montadora/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Montadora Kar</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Montadora K", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Veículo", "Listar", "Veiculo")</li>
                    <li>@Html.ActionLink("Peça","Listar","Peca")</li>
                    <li>@Html.ActionLink("Cliente", "Listar", "Cliente")</li>
                    <li>@Html.ActionLink("Fornecedor", "Listar", "Fornecedor")</li>
                    <li>@Html.ActionLink("Montador", "Listar", "Montador")</li>
                    <li>@Html.ActionLink("Cidade", "Listar", "Cidade")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Montadora K</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("scripts", required:false)
</body>
</html>