Montadora/Models/Montador.cs
using Montadora.Repository;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Montadora.Models
{
    public class Montador : Pessoa
    {
        [Display(Name="Salário")]
        public decimal Salario { get; set; }

        public IList<Montador> GetAll()
        {
            MontadorRepository objMontadorRep = new MontadorRepository();
            return objMontadorRep.SelecionarTodas();
        }
        public void Save()
        {
            MontadorRepository MontadorRep = new MontadorRepository();
            if (Id == 0)
            {
                MontadorRep.Salvar(this);
            }
            else
            {
                MontadorRep.Alterar(this);
            }
        }
        public IList<Montador> GetByName(string nomeBusca)
        {
            return new MontadorRepository().BuscarPorNome(nomeBusca);
        }
        public Montador FindById(int id)
        {
            MontadorRepository objMontadorRep = new MontadorRepository();
            Montador objMontador = new Montador();
            return objMontador = objMontadorRep.BuscarPorID(id);            
        }
        public void Delete(Montador m)
        {
            MontadorRepository objMontadorRep = new MontadorRepository();
            objMontadorRep.Deletar(m);
        }
        public IList<Montador> FindByName(string nomeBusca)
        {
            MontadorRepository objMontadorRep = new MontadorRepository();
            IList<Montador> listaDeMontadores = new List<Montador>();
            return listaDeMontadores = objMontadorRep.BuscarPorNome(nomeBusca);
        }
    }
}

Montadora/Controllers/MontadorController.cs
using Montadora.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Montadora.Controllers
{
    public class MontadorController : Controller
    {
        [HttpGet]
        public ActionResult Listar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Listar(string nomeBusca)
        {
            IList<Montador> listaDeMontadores = new Montador().GetByName(nomeBusca);
            return PartialView("_ListarMontador", listaDeMontadores);
        }
        [HttpGet]
        public ActionResult Novo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Novo(Montador m)
        {
            if (ModelState.IsValid)
            {
                m.Save();
                return RedirectToAction("Listar");
            }
            else
            {
                return View(m);
            }
        }
        [HttpGet]
        public ActionResult Deletar(int id)
        {
            Montador objMontador = new Montador().FindById(id);
            return View(objMontador);
        }
        [HttpPost]
        public ActionResult Deletar(Montador objMontador)
        {
            objMontador.Delete(objMontador);
            return RedirectToAction("Listar");
        }
        [HttpGet]
        public ActionResult Editar(int id)
        {
            Montador objMontador = new Montador().FindById(id);
            return View(objMontador);
        }
        [HttpPost]
        public ActionResult Editar(Montador objMontador)
        {
            objMontador.Save();
            return RedirectToAction("Listar");
        }
    }
}

Montadora/Views/Montador/Deletar.cshtml
@model Montadora.Models.Montador
@{
    ViewBag.Title = "Excluir Montador";
}
<h2>Você deseja realmente excluir o Montador: @Model.Nome ? </h2>
<hr />
@using (Html.BeginForm())
{
    @Html.HiddenFor(id => id.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.Nome): @Model.Nome
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Cpf): @Model.Cpf
    </div>
    <div class="form-group">
        <div class="col-md-offset-1">
            <input type="submit" value="Excluir" class="btn btn-danger" />
            @Html.ActionLink("Cancelar", "Listar", "", new { @class = "btn btn-primary" })
        </div>
    </div>
}

Montadora/Views/Montador/Editar.cshtml
@model Montadora.Models.Montador
@{
    ViewBag.Title = "Editar Montador";
}
<h2>Editar Montador</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.HiddenFor(id => id.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.Nome)
        @Html.EditorFor(model => model.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Cpf)
        @Html.EditorFor(model => model.Cpf, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Salario)
        @Html.EditorFor(model => model.Salario, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <div class="col-md-offset-1">
            <input type="submit" value="Salvar" class="btn btn-success" />
            @Html.ActionLink("Cancelar", "Listar", "", new { @class = "btn btn-default" })
        </div>
    </div>
}

Montadora/Views/Montador/Listar.cshtml
@model IEnumerable<Montadora.Models.Montador>
@{
    ViewBag.Title = "Listar";
}

<h3>Buscar Montadores</h3>
<hr />
<div class="col-md-offset-11">
    <p>
        @Html.ActionLink(" ", "Novo", null, new { @class = " glyphicon glyphicon-plus btn btn-primary", })
    </p>
</div>

<div class="row">
    <div class="col-md-3">
        <input type="text" name="nomeBusca" id="nomeBusca" class="form-control" placeholder="Informe o nome do montador..." />
    </div>
    <div class="col-lg-offset-3">
        <button type="submit" id="buscar" onclick="click" class="btn btn-primary"><i class=" glyphicon glyphicon-search"></i></button>
    </div>
</div>

<hr />
<div id="listaMontador">

</div>


@section scripts{
    <script>
        $("#buscar").on("click", function () {
            var resultado = $("#nomeBusca").val();

            $("#listaMontador").load('@Url.Action("Listar","Montador")', { montador: resultado })
        });
    </script>
}

Montadora/Views/Montador/Novo.cshtml
@model Montadora.Models.Montador
@{
    ViewBag.Title = "Novo Montador";
}

<h2>Nova Montador</h2>
<hr />
@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(model => model.Nome)
        @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Cpf)
        @Html.TextBoxFor(model => model.Cpf, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Salario)
        @Html.TextBoxFor(model => model.Salario, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <div class="col-md-offset-1">
            <input type="submit" value="Salvar" class="btn btn-success" />
            @Html.ActionLink("Cancelar", "Listar", "", new { @class = "btn btn-default" })
        </div>
    </div>
}

Montadora/Views/Montador/_ListarMontador.cshtml
@model IEnumerable<Montadora.Models.Montador>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Nome)</th>
            <th>@Html.DisplayNameFor(model => model.Cpf)</th>
            <th>@Html.DisplayNameFor(model => model.Salario)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>@Html.DisplayFor(i => item.Nome)</td>
                <td>@Html.DisplayFor(i => item.Cpf)</td>
                <td>@Html.DisplayFor(i => item.Salario)</td>
                <td>
                    @Html.ActionLink(" ", "Editar", new { id = item.Id }, new { @class = "glyphicon glyphicon-pencil btn btn-warning" })
                    @Html.ActionLink(" ", "Deletar", new { id = item.Id }, new { @class = "glyphicon glyphicon-trash btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>